//! Linux TUN tunnel implementation
//!
//! Creates and manages a TUN virtual network interface for WireGuard VPN on Linux.
//! Uses /dev/net/tun with IFF_TUN | IFF_NO_PI for raw IP packet I/O.

#![allow(dead_code)]

use std::net::Ipv4Addr;
use std::process::Command;
use std::str::FromStr;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::Arc;

use tokio::sync::{mpsc, RwLock};

use super::wireguard_new::WireGuardSession;
use crate::api::types::VpnConfig;
use crate::utils::redact_ip;

/// Run a command (no special flags needed on Linux — no console window issue)
fn cmd(program: &str) -> Command {
    crate::utils::hidden_cmd(program)
}

/// TUN device name prefix
const TUN_DEVICE_NAME: &str = "birdo0";

/// First line configure_dns writes when it pins /etc/resolv.conf. Also used to
/// RECOGNISE our own pin on unwind paths where the `Ok(pinned)` flag never
/// reached the caller (configure_dns erroring after the write, or a cancelled
/// start()) — see `resolv_conf_is_ours`.
const RESOLV_CONF_MARKER: &str = "# Generated by Birdo VPN";

/// F-001: dedicated chain for the steady-state IPv6 leak block. Deliberately
/// SEPARATE from the kill switch's BIRDO_KILLSWITCH chain so the two never
/// interfere — this block must persist for the whole Connected session, whereas
/// the kill-switch chain is torn down once the tunnel is healthy.
const IPV6_BLOCK_CHAIN: &str = "BIRDO_IPV6_LEAK_BLOCK";

/// Run an ip6tables command, tolerating ip6tables being absent (IPv4-only host).
/// Mirrors firewall_linux.rs's ip6tables() so behaviour is identical.
fn ip6t(args: &[&str]) -> Result<(), String> {
    // `-w`: wait for the xtables lock instead of failing instantly under
    // contention (firewalld, docker) — same as firewall_linux.rs's helpers.
    match cmd("ip6tables").arg("-w").args(args).output() {
        Ok(o) if o.status.success() => Ok(()),
        Ok(o) => Err(format!(
            "ip6tables {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&o.stderr).trim()
        )),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            tracing::debug!("ip6tables not present — skipping IPv6 leak block (IPv4-only host)");
            Ok(())
        }
        Err(e) => Err(format!("ip6tables spawn failed: {e}")),
    }
}

/// F-001: install a default-deny IPv6 egress block for the whole connect window.
///
/// Without this, any IPv6-capable app egresses via the physical NIC's untouched
/// IPv6 default route while the UI reports "Protected" — a continuous
/// de-anonymisation leak the kill switch never catches (WireGuard never drops,
/// so nothing trips). Windows has done this since the LEAK-2 fix (tunnel.rs);
/// this is the Linux port.
///
/// This is the DEFAULT state, not the final one. It is installed unconditionally
/// at tunnel start so every failure path fails closed, and lifted by
/// `remove_ipv6_leak_block` only once `configure_ipv6` has actually put the
/// tunnel's own v6 address and routes in place — which happens only when the
/// backend issued a `client_ipv6` (i.e. the node is genuinely dual-stack).
/// On an IPv4-only node the block simply stays for the whole session.
///
/// Loopback, link-local and NDP/ICMPv6 stay permitted so the host keeps working;
/// everything routable is dropped. Idempotent (flush + recreate each call).
pub(crate) fn install_ipv6_leak_block() -> Result<(), String> {
    let _ = ip6t(&["-N", IPV6_BLOCK_CHAIN]); // create (ignore "already exists")
    let _ = ip6t(&["-F", IPV6_BLOCK_CHAIN]); // clean slate
    ip6t(&["-A", IPV6_BLOCK_CHAIN, "-o", "lo", "-j", "ACCEPT"])?;
    // Link-local and link-scoped multicast only: this covers NDP (NS/NA/RS/RA),
    // DAD, MLD and DHCPv6, which is everything the host needs to stay functional.
    // NOTE: deliberately NO blanket `-p ipv6-icmp ACCEPT`. That would permit
    // ICMPv6 echo to GLOBAL destinations, i.e. `ping6 <any host>` would still
    // egress the physical NIC and disclose the real IPv6 address — a smaller
    // version of the very leak this chain exists to close. Inbound ICMPv6 (PMTUD
    // "Packet Too Big") is unaffected: this chain is hooked into OUTPUT only.
    ip6t(&["-A", IPV6_BLOCK_CHAIN, "-d", "fe80::/10", "-j", "ACCEPT"])?;
    ip6t(&["-A", IPV6_BLOCK_CHAIN, "-d", "ff02::/16", "-j", "ACCEPT"])?;
    // REJECT, not DROP: the packet is still never allowed out (identical leak
    // protection — the ICMPv6 rejection is generated locally), but the sender
    // fails IMMEDIATELY instead of waiting out a TCP timeout. A silent DROP
    // stalled our OWN dual-stack control-plane HTTPS (api.birdo.app publishes an
    // AAAA) and DoH until the request timeout, so a server switch could not
    // fetch its new config. Fall back to DROP if the REJECT target is
    // unavailable (some minimal kernels lack ip6t_REJECT) — never leave IPv6
    // unblocked just because we could not install the nicer variant.
    if ip6t(&[
        "-A",
        IPV6_BLOCK_CHAIN,
        "-j",
        "REJECT",
        "--reject-with",
        "icmp6-adm-prohibited",
    ])
    .is_err()
    {
        ip6t(&["-A", IPV6_BLOCK_CHAIN, "-j", "DROP"])?;
    }
    // Jump OUTPUT -> our chain (delete first so repeated starts don't stack).
    let _ = ip6t(&["-D", "OUTPUT", "-j", IPV6_BLOCK_CHAIN]);
    ip6t(&["-I", "OUTPUT", "1", "-j", IPV6_BLOCK_CHAIN])?;
    tracing::info!("F-001: IPv6 egress blocked for the connect window");
    Ok(())
}

/// F-001: lift the IPv6 block at teardown. Best-effort — never fail teardown.
///
/// Also used to reconcile state a crashed or failed run left behind: the chain
/// name is ours alone, so removing it is unconditionally safe and idempotent.
pub(crate) fn remove_ipv6_leak_block() {
    let _ = ip6t(&["-D", "OUTPUT", "-j", IPV6_BLOCK_CHAIN]);
    let _ = ip6t(&["-F", IPV6_BLOCK_CHAIN]);
    let _ = ip6t(&["-X", IPV6_BLOCK_CHAIN]);
    tracing::info!("F-001: IPv6 egress block removed");
}

/// Stores original DNS and default route info for restoration on disconnect
#[derive(Debug, Clone)]
struct NetworkSnapshot {
    /// Original DNS servers from /etc/resolv.conf or systemd-resolved
    dns_servers: Vec<String>,
    /// Original default gateway
    default_gateway: Option<String>,
    /// Original default interface (e.g. "eth0", "wlan0")
    default_interface: Option<String>,
    /// Whether systemd-resolved is available
    uses_systemd_resolved: bool,
    /// Original resolv.conf contents for fallback restoration
    resolv_conf_backup: Option<String>,
    /// True once configure_dns has OVERWRITTEN /etc/resolv.conf this session.
    /// This — not `uses_systemd_resolved` — is what drives the file restore on
    /// disconnect: the two signals disagree on real hosts (resolved unit
    /// active but resolv.conf a plain file), and restoring off the wrong one
    /// left the host pointed at dead tunnel resolvers.
    resolv_conf_pinned: bool,
}

/// Linux TUN tunnel for WireGuard VPN
pub struct LinuxTunnel {
    config: VpnConfig,
    running: Arc<AtomicBool>,
    bytes_sent: Arc<AtomicU64>,
    bytes_received: Arc<AtomicU64>,
    packets_sent: Arc<AtomicU64>,
    packets_received: Arc<AtomicU64>,
    wg_session: Arc<RwLock<Option<WireGuardSession>>>,
    shutdown_tx: Arc<RwLock<Option<mpsc::Sender<()>>>>,
    /// The TUN device name (e.g. "birdo0")
    tun_name: Arc<RwLock<Option<String>>>,
    /// The raw file descriptor for the TUN device
    tun_fd: Arc<RwLock<Option<i32>>>,
    /// Network snapshot for restoration on disconnect
    network_snapshot: Arc<RwLock<Option<NetworkSnapshot>>>,
    /// Whether to allow local network access while VPN is active
    local_network_sharing: bool,
    /// Endpoint IP for route exclusion
    endpoint_ip: Arc<RwLock<Option<String>>>,
}

impl LinuxTunnel {
    /// Create a new TUN tunnel with the given VPN configuration.
    pub async fn create(config: &VpnConfig, local_network_sharing: bool) -> Result<Self, String> {
        validate_config(config)?;

        Ok(Self {
            config: config.clone(),
            running: Arc::new(AtomicBool::new(false)),
            bytes_sent: Arc::new(AtomicU64::new(0)),
            bytes_received: Arc::new(AtomicU64::new(0)),
            packets_sent: Arc::new(AtomicU64::new(0)),
            packets_received: Arc::new(AtomicU64::new(0)),
            wg_session: Arc::new(RwLock::new(None)),
            shutdown_tx: Arc::new(RwLock::new(None)),
            tun_name: Arc::new(RwLock::new(None)),
            tun_fd: Arc::new(RwLock::new(None)),
            network_snapshot: Arc::new(RwLock::new(None)),
            local_network_sharing,
            endpoint_ip: Arc::new(RwLock::new(None)),
        })
    }

    /// Start the tunnel: create TUN device, configure routes/DNS, start packet loop.
    pub async fn start(&self) -> Result<(), String> {
        tracing::info!("Starting Linux TUN tunnel");

        if !crate::utils::elevation::is_elevated() {
            tracing::warn!("Tunnel requires root privileges for TUN/route configuration");
        }

        // Snapshot current network config for restoration
        let snapshot = capture_network_snapshot().await?;
        tracing::info!(
            "Captured network snapshot: gw={:?}, iface={:?}",
            snapshot.default_gateway.as_deref().map(|s| redact_ip(s)),
            snapshot.default_interface
        );
        *self.network_snapshot.write().await = Some(snapshot);

        // Create the TUN device
        let (tun_name, tun_fd) =
            create_tun_device().map_err(|e| format!("Failed to create TUN device: {}", e))?;
        tracing::info!("Created TUN device: {}", tun_name);

        *self.tun_name.write().await = Some(tun_name.clone());
        *self.tun_fd.write().await = Some(tun_fd);

        // Create WireGuard session BEFORE configuring routes.
        //
        // P1-dk-linux-no-drop-fd-leak-blackhole: from here on, every error
        // return goes through unwind_failed_start() — the fd stored above must
        // never outlive a failed start (the device it keeps alive owns the
        // split-default routes with no packet loop behind them: an IPv4
        // blackhole), and partially-installed routes/DNS must be rolled back.
        // Mirrors tunnel_macos.rs's close_fd_on_err, but reuses stop() so the
        // unwind cannot drift from the real teardown.
        let wg_session = match WireGuardSession::new(
            &self.config.private_key,
            &self.config.server_public_key,
            &self.config.endpoint,
            self.config.preshared_key.as_deref(),
            self.config.persistent_keepalive,
        )
        .await
        {
            Ok(session) => session,
            Err(e) => {
                self.unwind_failed_start().await;
                return Err(format!("Failed to create WireGuard session: {}", e));
            }
        };
        tracing::info!("WireGuard session created");

        let endpoint_ip = wg_session.endpoint_ip();
        tracing::info!(
            "WireGuard endpoint IP: {}",
            redact_ip(&endpoint_ip.to_string())
        );
        *self.endpoint_ip.write().await = Some(endpoint_ip.to_string());

        // Configure the TUN interface IP and bring it up
        if let Err(e) = configure_tun_address(&tun_name, &self.config.client_ip, &self.config.mtu) {
            self.unwind_failed_start().await;
            return Err(e);
        }

        // Configure routing
        if let Err(e) = configure_routes(
            &tun_name,
            &endpoint_ip.to_string(),
            &self.config.allowed_ips,
            self.local_network_sharing,
        )
        .await
        {
            // configure_routes can fail MID-LOOP with the endpoint route and
            // 0.0.0.0/1 already installed — the unwind's remove_routes (via
            // stop()) deletes exactly what went in; closing the fd alone would
            // leave the endpoint/LAN routes pointing at a stale gateway.
            self.unwind_failed_start().await;
            return Err(e);
        }

        // F-001 (P0): block IPv6 egress for the whole Connected session. Done here
        // — at tunnel start, INDEPENDENT of the kill-switch enabled/lockdown
        // setting — exactly as Windows does (tunnel.rs LEAK-2). The reactive kill
        // switch cannot cover this: it is torn down once the tunnel is healthy, and
        // an IPv6 leak never drops the (IPv4-only) tunnel so it never triggers.
        //
        // Block FIRST, unconditionally, then lift only if we can actually carry
        // IPv6 — so every failure path between here and a working dual-stack
        // tunnel fails CLOSED.
        if let Err(e) = install_ipv6_leak_block() {
            self.unwind_failed_start().await;
            return Err(e);
        }

        // Dual-stack: the fleet DOES have routable IPv6 now (nodes provisioned
        // with enable_ipv6 get a real /64), so when the backend issues a
        // client_ipv6 the correct behaviour is to ROUTE IPv6 through the tunnel,
        // not to black-hole it. Mirrors tunnel.rs (Windows) exactly: lift the
        // block immediately before the tunnel's own v6 address and routes go in,
        // and re-block if any of that fails.
        //
        // Absent client_ipv6 the block simply stays in force, which is the
        // leak-safe behaviour for an IPv4-only node.
        if self.config.client_ipv6.is_some() {
            match configure_ipv6(&tun_name, &self.config).await {
                Ok(()) => {
                    remove_ipv6_leak_block();
                    tracing::info!("IPv6 routed through the tunnel (dual-stack node)");
                }
                Err(e) => {
                    tracing::warn!("IPv6 routing setup failed ({}); leaving IPv6 blocked", e);
                }
            }
        }

        // Configure DNS
        let snapshot = self.network_snapshot.read().await;
        let uses_resolved = snapshot.as_ref().map_or(false, |s| s.uses_systemd_resolved);
        drop(snapshot);
        let pinned = match configure_dns(&self.config.dns, &tun_name, uses_resolved).await {
            Ok(pinned) => pinned,
            Err(e) => {
                // configure_dns can fail AFTER pinning /etc/resolv.conf (the
                // resolvectl step errors once the file is already written);
                // unwind_failed_start detects the marker and restores the backup.
                self.unwind_failed_start().await;
                return Err(e);
            }
        };
        if pinned {
            // Record "we overwrote /etc/resolv.conf" so restore_dns puts the
            // backup back — this flag, not uses_systemd_resolved, drives the
            // file restore (the two disagree on real hosts; see NetworkSnapshot).
            if let Some(snap) = self.network_snapshot.write().await.as_mut() {
                snap.resolv_conf_pinned = true;
            }
        }

        // Store WireGuard session
        *self.wg_session.write().await = Some(wg_session);
        self.running.store(true, Ordering::SeqCst);

        // Create shutdown channel
        let (shutdown_tx, shutdown_rx) = mpsc::channel::<()>(1);
        *self.shutdown_tx.write().await = Some(shutdown_tx);

        // Start packet processing loop
        let running = self.running.clone();
        let bytes_sent = self.bytes_sent.clone();
        let bytes_received = self.bytes_received.clone();
        let packets_sent = self.packets_sent.clone();
        let packets_received = self.packets_received.clone();
        let wg_session = self.wg_session.clone();
        let fd = tun_fd;

        tokio::spawn(async move {
            Self::packet_loop(
                fd,
                wg_session,
                running,
                bytes_sent,
                bytes_received,
                packets_sent,
                packets_received,
                shutdown_rx,
            )
            .await;
        });

        tracing::info!("Linux tunnel started successfully");
        Ok(())
    }

    /// Unwind a partially-configured start() on its error path.
    ///
    /// P1-dk-linux-no-drop-fd-leak-blackhole: every `?` after the TUN fd was
    /// stored used to return with the fd (and whatever routes/DNS had gone in)
    /// left behind — the device survived, still owning the split-default
    /// routes with no packet loop: a total IPv4 blackhole plus one leaked fd
    /// per failed connect. This reuses stop() — unconditional and best-effort
    /// on Linux — so the unwind removes exactly the subset of state the failed
    /// start managed to install and can never drift from the real teardown.
    async fn unwind_failed_start(&self) {
        // configure_dns can fail AFTER overwriting /etc/resolv.conf (the
        // resolvectl step errors once the file is already written), and its
        // Ok(pinned) flag is lost with the Err — so recognise our own marker
        // directly and record it, which is what drives restore_dns's file
        // restore inside stop().
        if resolv_conf_is_ours() {
            if let Some(snap) = self.network_snapshot.write().await.as_mut() {
                snap.resolv_conf_pinned = true;
            }
        }
        if let Err(e) = self.stop().await {
            tracing::warn!("Cleanup after a failed tunnel start also failed: {}", e);
        }
    }

    /// Stop the tunnel and restore network configuration.
    pub async fn stop(&self) -> Result<(), String> {
        tracing::info!("Stopping Linux TUN tunnel");

        self.running.store(false, Ordering::SeqCst);

        // Signal the packet loop to stop
        if let Some(tx) = self.shutdown_tx.write().await.take() {
            let _ = tx.send(()).await;
        }

        // Restore DNS
        if let Some(snapshot) = self.network_snapshot.read().await.as_ref() {
            restore_dns(snapshot);
        }

        // F-001: lift the IPv6 block. Best-effort so it can never fail teardown
        // (a stuck block would leave the host without IPv6 after disconnect).
        remove_ipv6_leak_block();

        // Remove routes. The snapshot supplies the gateway/interface the LAN
        // routes were added through, so their deletion can be qualified the same
        // way and cannot match a route belonging to something else.
        if let Some(ep_ip) = self.endpoint_ip.read().await.as_ref() {
            let snap = self.network_snapshot.read().await;
            let gw = snap.as_ref().and_then(|s| s.default_gateway.clone());
            let iface = snap.as_ref().and_then(|s| s.default_interface.clone());
            drop(snap);
            remove_routes(
                ep_ip,
                &self.config.allowed_ips,
                self.local_network_sharing,
                gw.as_deref(),
                iface.as_deref(),
            )
            .await;
        }

        // Close the TUN file descriptor (kernel auto-removes the device)
        if let Some(fd) = self.tun_fd.write().await.take() {
            let _ = unsafe { libc::close(fd) };
            tracing::info!("Closed TUN file descriptor");
        }

        *self.tun_name.write().await = None;
        *self.wg_session.write().await = None;

        tracing::info!("Linux tunnel stopped successfully");
        Ok(())
    }

    /// Check if the tunnel is currently running.
    pub fn is_running(&self) -> bool {
        self.running.load(Ordering::SeqCst)
    }

    /// Get tunnel statistics: (bytes_sent, bytes_received, packets_sent, packets_received)
    pub fn get_stats(&self) -> (u64, u64, u64, u64) {
        (
            self.bytes_sent.load(Ordering::Relaxed),
            self.bytes_received.load(Ordering::Relaxed),
            self.packets_sent.load(Ordering::Relaxed),
            self.packets_received.load(Ordering::Relaxed),
        )
    }

    /// Get current latency in milliseconds.
    pub async fn get_latency_ms(&self) -> Option<u32> {
        if let Some(session) = self.wg_session.read().await.as_ref() {
            session.get_latency_ms().await
        } else {
            None
        }
    }

    /// Measure latency to the VPN endpoint.
    pub async fn measure_latency(&self) -> Option<u32> {
        if let Some(session) = self.wg_session.read().await.as_ref() {
            session.measure_latency().await
        } else {
            None
        }
    }

    /// Get the client IP address.
    pub fn get_client_ip(&self) -> &str {
        &self.config.client_ip
    }

    /// Get the server endpoint address.
    pub fn get_endpoint(&self) -> &str {
        &self.config.endpoint
    }

    /// Packet processing loop: read from TUN, encrypt via WireGuard, send to server.
    ///
    /// Linux TUN with IFF_NO_PI provides raw IP packets — no protocol header unlike macOS utun.
    async fn packet_loop(
        tun_fd: i32,
        wg_session: Arc<RwLock<Option<WireGuardSession>>>,
        running: Arc<AtomicBool>,
        bytes_sent: Arc<AtomicU64>,
        bytes_received: Arc<AtomicU64>,
        packets_sent: Arc<AtomicU64>,
        packets_received: Arc<AtomicU64>,
        mut shutdown_rx: mpsc::Receiver<()>,
    ) {
        tracing::info!("Packet loop started on TUN fd={}", tun_fd);

        const MAX_PACKET_SIZE: usize = 65536;

        // Same cadence Windows uses (tunnel.rs). 250ms is comfortably finer than
        // boringtun's shortest timer, so no deadline is ever missed.
        // Idle backoff, mirroring Windows (tunnel.rs). Both fds are O_NONBLOCK
        // and recv_packet returns Ok(None) immediately on WouldBlock, so an idle
        // tunnel previously spun a core at 100% and churned the blocking pool
        // with a spawn_blocking round trip per iteration, forever. Any packet in
        // either direction resets the counter, so only the FIRST packet after a
        // sustained idle pays the extra latency.
        let mut idle_cycles: u32 = 0;
        const IDLE_THRESHOLD: u32 = 100;
        const DEEP_IDLE_THRESHOLD: u32 = 2_000;
        const SLOW_POLL_US: u64 = 500;
        const DEEP_POLL_US: u64 = 5_000;
        // Drain up to this many decrypted packets per wake, so a burst is not
        // paced one packet per loop iteration.
        const MAX_BATCH_SIZE: usize = 64;
        let mut last_timer_update = std::time::Instant::now();
        const TIMER_INTERVAL: std::time::Duration = std::time::Duration::from_millis(250);

        loop {
            let mut did_work = false;
            if !running.load(Ordering::SeqCst) {
                tracing::info!("Packet loop: running flag cleared, exiting");
                break;
            }

            tokio::select! {
                _ = shutdown_rx.recv() => {
                    tracing::info!("Packet loop: shutdown signal received");
                    break;
                }
                // Read from TUN (async via spawn_blocking for the fd read)
                result = tokio::task::spawn_blocking({
                    let fd = tun_fd;
                    // Allocate a fresh zeroed buffer per read. alloc_zeroed for a
                    // large buffer is typically backed by lazily-faulted zero pages,
                    // avoiding the eager 64KiB memcpy that `read_buf.clone()` incurred.
                    // Behaviour is identical: the buffer is overwritten by `read` up to
                    // `n` bytes and then truncated to `n`, so initial contents never matter.
                    let mut buf = vec![0u8; MAX_PACKET_SIZE];
                    move || {
                        let n = unsafe { libc::read(fd, buf.as_mut_ptr() as *mut libc::c_void, buf.len()) };
                        if n > 0 {
                            buf.truncate(n as usize);
                            Some(buf)
                        } else if n < 0 {
                            let err = std::io::Error::last_os_error();
                            if err.raw_os_error() != Some(libc::EAGAIN) {
                                tracing::debug!("TUN read error: {}", err);
                            }
                            None
                        } else {
                            None
                        }
                    }
                }) => {
                    if let Ok(Some(ip_packet)) = result {
                        did_work = true;
                        // Linux TUN with IFF_NO_PI: data is already a raw IP packet
                        let packet_len = ip_packet.len() as u64;

                        if let Some(session) = wg_session.read().await.as_ref() {
                            match session.send_packet(&ip_packet).await {
                                Ok(_) => {
                                    bytes_sent.fetch_add(packet_len, Ordering::Relaxed);
                                    packets_sent.fetch_add(1, Ordering::Relaxed);
                                }
                                Err(e) => {
                                    tracing::debug!("Failed to send WG packet: {}", e);
                                }
                            }
                        }
                    }
                }
            }

            // Read from WireGuard and write decrypted packets to TUN
            for _ in 0..MAX_BATCH_SIZE {
                if let Some(session) = wg_session.read().await.as_ref() {
                    if let Ok(Some(decrypted)) = session.recv_packet().await {
                        did_work = true;
                        let packet_len = decrypted.len() as u64;

                        // Linux TUN with IFF_NO_PI: write raw IP packet directly (no header)
                        let fd = tun_fd;
                        let buf = decrypted;
                        let buf_len = buf.len();
                        let write_result = tokio::task::spawn_blocking(move || {
                            let written = unsafe {
                                libc::write(fd, buf.as_ptr() as *const libc::c_void, buf.len())
                            };
                            if written < 0 {
                                tracing::debug!(
                                    "TUN write error: {}",
                                    std::io::Error::last_os_error()
                                );
                            } else if (written as usize) < buf.len() {
                                tracing::warn!(
                                    "Partial TUN write: {} of {} bytes",
                                    written,
                                    buf.len()
                                );
                            }
                            written
                        })
                        .await;

                        // Only count statistics when the full packet was written to TUN.
                        // Partial writes or errors must not inflate received counters.
                        if let Ok(written) = write_result {
                            if written >= 0 && (written as usize) == buf_len {
                                bytes_received.fetch_add(packet_len, Ordering::Relaxed);
                                packets_received.fetch_add(1, Ordering::Relaxed);
                            }
                        }
                    } else {
                        break; // nothing queued — stop draining
                    }
                } else {
                    break;
                }
            }

            // Drive boringtun's timers — WITHOUT this the session dies.
            //
            // boringtun advances all session state inside update_timers():
            // persistent keepalives, REKEY_AFTER_TIME rekeys, and dead-peer
            // detection. `encapsulate` reads the current keypair with no age
            // check, so once the server discards it at REJECT_AFTER_TIME the
            // client keeps happily encrypting to a session that no longer exists
            // — upload appears to work, download stops, and there is no
            // client-side recovery. Windows found this (FIX-DL, tunnel.rs:1834)
            // and fixed it; the Unix tunnels were never given the same tick, so
            // the keepalive plumbed in at start() was never actually emitted.
            //
            // The fd is O_NONBLOCK, so this is reached every iteration even when
            // the tunnel is completely idle — which is exactly when it matters.
            if last_timer_update.elapsed() >= TIMER_INTERVAL {
                last_timer_update = std::time::Instant::now();
                if let Some(session) = wg_session.read().await.as_ref() {
                    if let Err(e) = session.update_timers().await {
                        tracing::trace!("Timer update error: {}", e);
                    }
                }
            }

            if did_work {
                idle_cycles = 0;
            } else {
                idle_cycles = idle_cycles.saturating_add(1);
                if idle_cycles > DEEP_IDLE_THRESHOLD {
                    tokio::time::sleep(std::time::Duration::from_micros(DEEP_POLL_US)).await;
                } else if idle_cycles > IDLE_THRESHOLD {
                    tokio::time::sleep(std::time::Duration::from_micros(SLOW_POLL_US)).await;
                }
            }
        }

        tracing::info!("Packet loop exited");
    }
}

/// LAST-RESORT teardown, mirroring UtunTunnel's Drop (tunnel_macos.rs). start()
/// now unwinds its own error returns, but the manager wraps create()+start() in
/// CONNECT_TIMEOUT and DROPS the future on expiry — no error path ever runs,
/// the half-built tunnel is simply dropped. Without a Drop the TUN fd leaked,
/// and a leaked fd keeps birdo0 alive still owning the 0.0.0.0/1 + 128.0.0.0/1
/// half-defaults with no packet loop behind them: a total IPv4 blackhole the
/// user cannot recover from inside the app, plus one leaked descriptor per
/// failed connect. Closing the fd destroys the device and the kernel withdraws
/// every route through it.
impl Drop for LinuxTunnel {
    fn drop(&mut self) {
        // Drop cannot await. try_write is enough: by the time the tunnel is
        // being dropped nothing else legitimately holds this lock, and failing
        // to acquire it must never panic or block a teardown.
        let fd = match self.tun_fd.try_write() {
            Ok(mut guard) => guard.take(),
            Err(_) => None,
        };
        let Some(fd) = fd else {
            return; // stop()/unwind already ran — nothing leaked
        };
        let _ = unsafe { libc::close(fd) };
        tracing::warn!(
            "LinuxTunnel dropped with the TUN fd still open — closed it to \
             destroy the device and release its routes"
        );
        // A cancellation can also strike after /etc/resolv.conf was pinned but
        // before running ever became true — the pinned file outlives the
        // device and leaves every lookup on the machine pointing at tunnel
        // resolvers that no longer exist. Restore the backup, but only when
        // the file is provably ours.
        if resolv_conf_is_ours() {
            if let Ok(guard) = self.network_snapshot.try_read() {
                if let Some(snap) = guard.as_ref() {
                    let mut snap = snap.clone();
                    snap.resolv_conf_pinned = true;
                    restore_dns(&snap);
                }
            }
        }
    }
}

// ──────────────────────────────────────────────────────────────
// Platform-specific helper functions
// ──────────────────────────────────────────────────────────────

/// Validate all VPN config values before they reach system commands.
fn validate_config(config: &VpnConfig) -> Result<(), String> {
    Ipv4Addr::from_str(&config.client_ip)
        .map_err(|_| format!("Invalid client_ip: '{}'", config.client_ip))?;

    let endpoint_host = config
        .endpoint
        .split(':')
        .next()
        .ok_or_else(|| "Invalid endpoint format: missing host".to_string())?;
    if endpoint_host.parse::<Ipv4Addr>().is_err() {
        if endpoint_host.is_empty()
            || endpoint_host.len() > 253
            || !endpoint_host
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '-')
            || endpoint_host.starts_with('-')
            || endpoint_host.starts_with('.')
        {
            return Err(format!("Invalid endpoint hostname: '{}'", endpoint_host));
        }
    }

    for dns in &config.dns {
        Ipv4Addr::from_str(dns).map_err(|_| format!("Invalid DNS address: '{}'", dns))?;
    }

    for cidr in &config.allowed_ips {
        let parts: Vec<&str> = cidr.split('/').collect();
        if parts.len() != 2 {
            return Err(format!("Invalid CIDR format: '{}'", cidr));
        }
        Ipv4Addr::from_str(parts[0]).map_err(|_| format!("Invalid network in CIDR: '{}'", cidr))?;
        let prefix: u8 = parts[1]
            .parse()
            .map_err(|_| format!("Invalid prefix in CIDR: '{}'", cidr))?;
        if prefix > 32 {
            return Err(format!("Prefix out of range in CIDR: '{}'", cidr));
        }
    }

    if config.mtu < 576 || config.mtu > 9000 {
        return Err(format!("Invalid MTU: {} (expected 576-9000)", config.mtu));
    }

    // P1-dk-allowedips-no-default-coverage: the CIDRs above are only
    // syntax-checked; also refuse a scope that does not cover the full address
    // space (defense in depth — build_vpn_config already enforces this at the
    // choke point every connect path funnels through).
    crate::vpn::validate_tunnel_scope(config)?;

    Ok(())
}

/// Create a Linux TUN device via /dev/net/tun ioctl.
///
/// Uses IFF_TUN | IFF_NO_PI for raw IP packet I/O (no protocol info header).
/// Returns (tun_name, raw_fd) on success.
fn create_tun_device() -> Result<(String, i32), String> {
    // struct ifreq — only the fields we need
    #[repr(C)]
    struct IfReq {
        ifr_name: [u8; libc::IFNAMSIZ],
        ifr_flags: libc::c_short,
        _pad: [u8; 22], // padding to match struct size
    }

    const IFF_TUN: libc::c_short = 0x0001;
    const IFF_NO_PI: libc::c_short = 0x1000;
    // TUNSETIFF ioctl number: _IOW('T', 202, int)
    const TUNSETIFF: libc::c_ulong = 0x400454CA;

    // Open /dev/net/tun
    let tun_path = std::ffi::CString::new("/dev/net/tun")
        .map_err(|_| "Invalid TUN device path".to_string())?;

    let fd = unsafe { libc::open(tun_path.as_ptr(), libc::O_RDWR) };
    if fd < 0 {
        return Err(format!(
            "Failed to open /dev/net/tun: {} (are you root? is the tun module loaded?)",
            std::io::Error::last_os_error()
        ));
    }

    // Prepare ifreq
    let mut ifr = IfReq {
        ifr_name: [0u8; libc::IFNAMSIZ],
        ifr_flags: IFF_TUN | IFF_NO_PI,
        _pad: [0u8; 22],
    };

    // Set device name
    let name_bytes = TUN_DEVICE_NAME.as_bytes();
    if name_bytes.len() >= libc::IFNAMSIZ {
        unsafe { libc::close(fd) };
        return Err("TUN device name too long".to_string());
    }
    ifr.ifr_name[..name_bytes.len()].copy_from_slice(name_bytes);

    // Create the device
    let ret = unsafe { libc::ioctl(fd, TUNSETIFF, &mut ifr as *mut IfReq) };
    if ret < 0 {
        let err = std::io::Error::last_os_error();
        unsafe { libc::close(fd) };
        return Err(format!("ioctl TUNSETIFF failed: {}", err));
    }

    // Extract actual device name from ifreq
    let name_end = ifr
        .ifr_name
        .iter()
        .position(|&b| b == 0)
        .unwrap_or(libc::IFNAMSIZ);
    let tun_name = String::from_utf8_lossy(&ifr.ifr_name[..name_end]).to_string();

    // Set non-blocking mode
    let flags = unsafe { libc::fcntl(fd, libc::F_GETFL) };
    if flags >= 0 {
        let set_ret = unsafe { libc::fcntl(fd, libc::F_SETFL, flags | libc::O_NONBLOCK) };
        if set_ret < 0 {
            tracing::warn!(
                "Failed to set O_NONBLOCK on TUN fd: {} (device may remain blocking)",
                std::io::Error::last_os_error()
            );
        }
    } else {
        tracing::warn!(
            "fcntl F_GETFL failed on TUN fd: {} (could not set non-blocking mode)",
            std::io::Error::last_os_error()
        );
    }

    tracing::info!("Successfully created TUN device: {} (fd={})", tun_name, fd);
    Ok((tun_name, fd))
}

/// Configure the TUN interface IP address and MTU using `ip` command.
fn configure_tun_address(tun_name: &str, client_ip: &str, mtu: &u16) -> Result<(), String> {
    // Validate tun_name to prevent command injection
    if !tun_name.chars().all(|c| c.is_ascii_alphanumeric()) {
        return Err(format!("Invalid TUN device name: {}", tun_name));
    }

    // ip addr add <client_ip>/32 dev <tun_name>
    let output = cmd("ip")
        .args(["addr", "add", &format!("{}/32", client_ip), "dev", tun_name])
        .output()
        .map_err(|e| format!("Failed to configure TUN address: {}", e))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        // RTNETLINK File exists = address already assigned, not fatal
        if !stderr.contains("File exists") {
            return Err(format!("ip addr add failed: {}", stderr));
        }
    }
    tracing::info!("Configured {} with IP {}", tun_name, redact_ip(client_ip));

    // ip link set <tun_name> mtu <mtu> up
    let output = cmd("ip")
        .args(["link", "set", tun_name, "mtu", &mtu.to_string(), "up"])
        .output()
        .map_err(|e| format!("Failed to bring up TUN interface: {}", e))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("ip link set failed: {}", stderr));
    }

    Ok(())
}

/// Configure routing to send traffic through the VPN tunnel.
/// Give the TUN device its IPv6 address and route IPv6 through it.
///
/// Called ONLY when the backend issued a `client_ipv6` (i.e. the node is
/// genuinely dual-stack). Runs while the IPv6 leak block is still in force —
/// ip6tables filters packets, it does not prevent address or route
/// configuration — so a failure part-way through leaves IPv6 blocked rather
/// than leaking. The caller lifts the block only after this returns Ok.
///
/// Routes `::/1` + `8000::/1` rather than `::/0`, for the same reason the IPv4
/// path splits the default route: two more-specific routes beat the host's
/// existing `::/0` without deleting it, so teardown does not have to restore it.
async fn configure_ipv6(tun_name: &str, config: &VpnConfig) -> Result<(), String> {
    if !tun_name.chars().all(|c| c.is_ascii_alphanumeric()) {
        return Err(format!("Invalid TUN device name: {}", tun_name));
    }
    let client_ipv6 = config
        .client_ipv6
        .as_deref()
        .ok_or_else(|| "configure_ipv6 called without a client_ipv6".to_string())?;

    // Accept "addr" or "addr/prefix"; normalise to a /128 host address on the
    // tunnel, matching how the IPv4 side assigns /32.
    let addr = client_ipv6.split('/').next().unwrap_or(client_ipv6);
    if addr.parse::<std::net::Ipv6Addr>().is_err() {
        return Err(format!("Invalid client IPv6 address: {}", addr));
    }

    let output = cmd("ip")
        .args([
            "-6",
            "addr",
            "add",
            &format!("{}/128", addr),
            "dev",
            tun_name,
        ])
        .output()
        .map_err(|e| format!("Failed to configure TUN IPv6 address: {}", e))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        if !stderr.contains("File exists") {
            return Err(format!("ip -6 addr add failed: {}", stderr));
        }
    }

    // Expand any default-scoped entry into ::/1 + 8000::/1.
    //
    // This MUST happen for whatever the backend actually sends, not only when the
    // list is empty. The backend always sends `::/0` (vpn.service.ts), so an
    // is-empty fallback would be dead code — and using `::/0` verbatim is worse
    // than useless here: on any normal SLAAC host the kernel already holds a
    // `::/0` default, so `ip -6 route add ::/0 dev <tun>` returns "File exists".
    // Swallowing that (as the IPv4 path does) would make configure_ipv6 report
    // success with NO tunnel route installed, and the caller would then lift the
    // leak block — leaving the physical default winning and nothing blocking it.
    // That is strictly worse than never having routed v6 at all.
    //
    // Two more-specific halves beat an existing ::/0 on longest-prefix match
    // without deleting it, so teardown has nothing to restore. Same trick the
    // IPv4 side uses.
    let v6_routes: Vec<String> = if config.allowed_ips_v6.is_empty() {
        vec!["::/1".to_string(), "8000::/1".to_string()]
    } else {
        config
            .allowed_ips_v6
            .iter()
            .flat_map(|r| {
                if r.trim() == "::/0" {
                    vec!["::/1".to_string(), "8000::/1".to_string()]
                } else {
                    vec![r.clone()]
                }
            })
            .collect()
    };

    for route in &v6_routes {
        // Same shape of validation the IPv4 path applies to allowed_ips, so a
        // malformed value from the backend can never reach the `ip` command line.
        let parts: Vec<&str> = route.split('/').collect();
        if parts.len() != 2 {
            return Err(format!("Invalid IPv6 CIDR format: '{}'", route));
        }
        parts[0]
            .parse::<std::net::Ipv6Addr>()
            .map_err(|_| format!("Invalid network in IPv6 CIDR: '{}'", route))?;
        let prefix: u8 = parts[1]
            .parse()
            .map_err(|_| format!("Invalid prefix in IPv6 CIDR: '{}'", route))?;
        if prefix > 128 {
            return Err(format!("Prefix out of range in IPv6 CIDR: '{}'", route));
        }
        let output = cmd("ip")
            .args(["-6", "route", "add", route, "dev", tun_name])
            .output()
            .map_err(|e| format!("Failed to add IPv6 route {}: {}", route, e))?;
        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            // Deliberately do NOT tolerate "File exists" here, unlike the IPv4
            // path. After the split above, a collision means something else
            // already owns ::/1 or 8000::/1 on this host — so our route is not
            // in place, and reporting success would cause the caller to lift the
            // leak block over an unrouted tunnel. Fail instead: the block stays,
            // and the user gets working IPv4 with IPv6 safely dead.
            return Err(format!(
                "ip -6 route add {} failed: {}",
                route,
                stderr.trim()
            ));
        }
    }

    // Confirm the tunnel actually won the route, rather than trusting exit codes.
    // A route add can succeed and still lose: with a pre-existing default at a
    // better metric the kernel accepts the new route and keeps preferring the old
    // one. `ip -6 route get` asks the kernel what it would ACTUALLY do, which is
    // the only answer that matters before we take the leak block down.
    let probe = cmd("ip")
        .args(["-6", "route", "get", "2606:4700:4700::1111"])
        .output()
        .map_err(|e| format!("Failed to verify IPv6 routing: {}", e))?;
    let probe_out = String::from_utf8_lossy(&probe.stdout);
    if !probe.status.success() || !probe_out.contains(tun_name) {
        return Err(format!(
            "IPv6 route verification failed: kernel would not route via {} ({})",
            tun_name,
            probe_out.trim()
        ));
    }

    tracing::info!(
        "Configured {} with IPv6 and {} route(s)",
        tun_name,
        v6_routes.len()
    );
    Ok(())
}

/// Expand a default route into two halves, leaving everything else untouched.
///
/// The Linux FIB keys on (destination, metric), so a second `0.0.0.0/0` only
/// installs when the host default has a non-zero metric. Against a metric-0
/// default (dhclient, ifupdown, containers, netplan without `metric:`) the add
/// returns "File exists" — which the old code SWALLOWED, so the tunnel reported
/// Connected while every packet left via the physical NIC.
///
/// `0.0.0.0/1` + `128.0.0.0/1` cover the same space but are MORE SPECIFIC, so
/// longest-prefix match picks them regardless of metric, without deleting the
/// host default — so teardown has nothing to restore.
///
/// Shared by configure_routes and remove_routes so the two can never disagree
/// about what was installed.
/// Networks routed around the tunnel when Local Network Sharing is on.
///
/// Shared between install and teardown so the two cannot drift. These used to
/// be installed and then NEVER removed — leaving routes pointing at a gateway
/// that stops existing the moment the user changes network.
const LAN_SHARING_CIDRS: [&str; 4] = [
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16",
    "169.254.0.0/16",
];
fn expand_default_v4(allowed_ips: &[String]) -> Vec<String> {
    allowed_ips
        .iter()
        .flat_map(|cidr| match cidr.trim() {
            "0.0.0.0/0" => vec!["0.0.0.0/1".to_string(), "128.0.0.0/1".to_string()],
            other => vec![other.to_string()],
        })
        .collect()
}

async fn configure_routes(
    tun_name: &str,
    endpoint_ip: &str,
    allowed_ips: &[String],
    local_network_sharing: bool,
) -> Result<(), String> {
    // Get current default gateway for endpoint route
    let default_gw = get_default_gateway()?;
    let default_iface = get_default_interface()?;
    tracing::info!(
        "Default gateway: {} via {}",
        redact_ip(&default_gw),
        default_iface
    );

    // Add a specific route for the VPN endpoint via the real gateway
    // so WireGuard UDP packets don't get caught in the VPN tunnel
    let output = cmd("ip")
        .args([
            "route",
            "add",
            &format!("{}/32", endpoint_ip),
            "via",
            &default_gw,
            "dev",
            &default_iface,
        ])
        .output()
        .map_err(|e| format!("Failed to add endpoint route: {}", e))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        // MUST be fatal (except an existing identical route). Once the default
        // below is genuinely captured, a missing endpoint route sends WireGuard's
        // own outer UDP back into the tunnel — an encapsulation loop that reaches
        // Connected and carries zero traffic. Warning here would convert a visible
        // failure into an invisible one.
        if !stderr.contains("File exists") {
            return Err(format!(
                "Failed to pin the endpoint route: {}",
                stderr.trim()
            ));
        }
    }

    // Add routes for allowed_ips via the TUN interface
    let allowed_ips = expand_default_v4(allowed_ips);
    for cidr in &allowed_ips {
        let output = cmd("ip")
            .args(["route", "add", cidr, "dev", tun_name])
            .output()
            .map_err(|e| format!("Failed to add route for {}: {}", cidr, e))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            // Fatal now that defaults are split. Before the split a `0.0.0.0/0`
            // collision was routine and swallowing it looked harmless; after it, a
            // collision on `0.0.0.0/1` or `128.0.0.0/1` means the tunnel did NOT
            // capture traffic, and continuing would report Connected while
            // everything egresses the physical NIC.
            return Err(format!(
                "Failed to route {} into the tunnel: {}",
                cidr,
                stderr.trim()
            ));
        }
    }

    // If local network sharing is enabled, add RFC1918 routes via the real gateway
    if local_network_sharing {
        // 169.254/16 included for mDNS/Bonjour, matching Windows. Without it
        // printer and AirPlay DISCOVERY fails even though the LAN itself is
        // reachable, which reads as "Local Network Sharing is broken".
        let rfc1918 = LAN_SHARING_CIDRS;
        for cidr in &rfc1918 {
            let _ = cmd("ip")
                .args([
                    "route",
                    "add",
                    cidr,
                    "via",
                    &default_gw,
                    "dev",
                    &default_iface,
                ])
                .output();
        }
        tracing::info!("Added local network sharing routes (RFC1918)");
    }

    Ok(())
}

/// Configure DNS servers on Linux.
///
/// Prefers systemd-resolved (resolvectl) when available, falls back to /etc/resolv.conf.
/// Is systemd-resolved ACTUALLY the resolver applications use on this host?
///
/// `systemctl is-active systemd-resolved` answers a different question — whether
/// the unit is running — and the two diverge constantly: Ubuntu Server images with
/// a replaced resolv.conf, Debian with `resolvconf`, NetworkManager with
/// `dns=default`, WSL, containers. On all of those, resolved runs, the old code
/// took the resolvectl branch, configured DNS on the tun link only, left
/// /etc/resolv.conf untouched — and EVERY query on the machine kept going to the
/// original resolver while the UI said Connected. With Local Network Sharing on,
/// RFC1918 is routed via the real gateway, so a query to a router resolver leaves
/// the physical NIC in plaintext.
///
/// The reliable signal is what /etc/resolv.conf actually points at: the stub
/// resolver 127.0.0.53, or a file under /run/systemd/resolve/ once symlinks are
/// followed.
fn resolv_conf_uses_resolved() -> bool {
    if let Ok(target) = std::fs::canonicalize("/etc/resolv.conf") {
        if target.starts_with("/run/systemd/resolve/") {
            return true;
        }
    }
    match std::fs::read_to_string("/etc/resolv.conf") {
        Ok(contents) => contents
            .lines()
            .filter(|l| l.trim_start().starts_with("nameserver"))
            .any(|l| l.contains("127.0.0.53")),
        Err(_) => false,
    }
}

/// Returns `Ok(true)` when /etc/resolv.conf was OVERWRITTEN (the caller must
/// record that so restore_dns knows to put the backup back), `Ok(false)` when
/// only resolvectl was configured.
async fn configure_dns(
    dns_servers: &[String],
    tun_name: &str,
    uses_resolved: bool,
) -> Result<bool, String> {
    // Deliberately configure BOTH paths rather than choosing one.
    //
    // Picking a branch is what caused the leak: whichever signal you trust, some
    // real distro disagrees with it. On Fedora/Arch, `resolve` in nsswitch.conf
    // makes the resolvectl branch authoritative EVEN WITH a non-stub resolv.conf,
    // so switching to resolv.conf-only would regress those. Doing both is correct
    // everywhere and costs one extra file write.
    let stub_in_use = resolv_conf_uses_resolved();
    if uses_resolved && !stub_in_use {
        tracing::warn!(
            "systemd-resolved is running but /etc/resolv.conf does not point at it — configuring BOTH so DNS cannot bypass the tunnel"
        );
    }

    // Pin resolv.conf too, unless it IS the systemd stub (rewriting the stub file
    // would fight resolved and break resolution once we revert).
    let mut pinned_file = false;
    if !stub_in_use {
        let mut contents = format!("{} — will be restored on disconnect\n", RESOLV_CONF_MARKER);
        for dns in dns_servers {
            contents.push_str(&format!(
                "nameserver {}
",
                dns
            ));
        }
        // Temp file + rename: a reader never sees a half-written file, and a
        // SYMLINKED resolv.conf is replaced rather than followed — following it
        // would rewrite whatever it points at, including a /run file owned by
        // another daemon.
        let tmp = "/etc/.resolv.conf.birdo";
        match std::fs::write(tmp, &contents).and_then(|_| std::fs::rename(tmp, "/etc/resolv.conf"))
        {
            Ok(()) => {
                pinned_file = true;
                tracing::info!("Pinned /etc/resolv.conf to the tunnel resolvers");
            }
            Err(e) => {
                let _ = std::fs::remove_file(tmp);
                // Survivable IF resolved is genuinely in charge; otherwise nothing
                // is protecting DNS and we must fail the connect.
                if !uses_resolved {
                    return Err(format!("Failed to write /etc/resolv.conf: {}", e));
                }
                tracing::warn!(
                    "Could not pin /etc/resolv.conf ({}), relying on systemd-resolved",
                    e
                );
            }
        }
    }

    if uses_resolved {
        // systemd-resolved: set DNS for our TUN interface
        let mut args = vec!["dns".to_string(), tun_name.to_string()];
        args.extend(dns_servers.iter().cloned());

        let output = cmd("resolvectl")
            .args(&args)
            .output()
            .map_err(|e| format!("resolvectl dns failed: {}", e))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(format!("resolvectl dns failed: {}", stderr));
        }

        // Set our TUN as the default route for DNS (highest priority)
        let output = cmd("resolvectl")
            .args(["domain", tun_name, "~."])
            .output()
            .map_err(|e| format!("resolvectl domain failed: {}", e))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            tracing::warn!("resolvectl domain warning: {}", stderr);
        }

        tracing::info!(
            "Configured DNS via systemd-resolved on {}: {:?}",
            tun_name,
            dns_servers
        );
    }
    // No `else` branch any more: /etc/resolv.conf is pinned above on every host
    // where that is the right thing to do, INCLUDING when systemd-resolved is
    // running but is not what applications actually consult. Choosing one branch
    // is precisely what allowed DNS to bypass the tunnel entirely.

    Ok(pinned_file)
}

/// Is the CURRENT /etc/resolv.conf one that configure_dns wrote?
///
/// Used by the unwind paths where the `Ok(pinned)` flag never reached start():
/// configure_dns failing after the write, or a cancelled start() being dropped.
fn resolv_conf_is_ours() -> bool {
    std::fs::read_to_string("/etc/resolv.conf")
        .map(|c| c.starts_with(RESOLV_CONF_MARKER))
        .unwrap_or(false)
}

/// Restore original DNS configuration.
///
/// Deliberately synchronous (it never awaited anything): it must be callable
/// from LinuxTunnel's Drop, which cannot await.
fn restore_dns(snapshot: &NetworkSnapshot) {
    // Mirror configure_dns: it pins BOTH resolvectl and /etc/resolv.conf on
    // hosts where resolved is running but is not what applications consult, so
    // restore must undo BOTH.
    if snapshot.uses_systemd_resolved {
        // systemd-resolved: revert the TUN interface DNS (device is being torn down,
        // systemd-resolved will automatically drop configuration for removed interfaces)
        let _ = cmd("resolvectl").args(["revert", TUN_DEVICE_NAME]).output();
        tracing::info!("Reverted systemd-resolved DNS for {}", TUN_DEVICE_NAME);
    }

    // Drive the FILE restore off "did we write it", not off the resolved
    // check. configure_dns overwrites /etc/resolv.conf whenever it is not the
    // systemd stub — including with the resolved unit active — and the two
    // signals disagree on real hosts (see resolv_conf_uses_resolved). The old
    // uses_systemd_resolved branch carried backup=None on exactly those hosts,
    // so the tunnel resolvers were never removed from the file: DNS dead
    // system-wide after disconnect until a reboot or a network re-plug.
    //
    // When we never touched the file (stub in use, or the write failed and we
    // relied on resolved) there is nothing to undo — and restoring a stub
    // backup here would be wrong, which the pinned flag makes impossible:
    // configure_dns never pins over the stub.
    if !snapshot.resolv_conf_pinned {
        return;
    }
    if let Some(ref backup) = snapshot.resolv_conf_backup {
        // Restore original /etc/resolv.conf
        let _ = std::fs::write("/etc/resolv.conf", backup);
        tracing::info!("Restored /etc/resolv.conf from backup");
    } else {
        // We overwrote the file but its original bytes were unreadable at
        // snapshot time. Best effort: write back the original DNS servers.
        let mut contents = String::new();
        if snapshot.dns_servers.is_empty() {
            // No original DNS — write a reasonable default
            contents.push_str("nameserver 1.1.1.1\nnameserver 8.8.8.8\n");
        } else {
            for dns in &snapshot.dns_servers {
                contents.push_str(&format!("nameserver {}\n", dns));
            }
        }
        let _ = std::fs::write("/etc/resolv.conf", contents);
        tracing::info!("Restored /etc/resolv.conf from snapshot");
    }
}

/// Remove VPN-specific routes.
async fn remove_routes(
    endpoint_ip: &str,
    allowed_ips: &[String],
    local_network_sharing: bool,
    default_gateway: Option<&str>,
    default_interface: Option<&str>,
) {
    // Remove endpoint route
    let _ = cmd("ip")
        .args(["route", "del", &format!("{}/32", endpoint_ip)])
        .output();

    // Remove allowed_ip routes.
    //
    // Expanded through the SAME helper configure_routes used, so we delete exactly
    // the routes we installed. Previously this emitted `ip route del 0.0.0.0/0`,
    // which on a metric-0 host does not match anything we added (the add had
    // failed) and instead deletes the HOST'S OWN default — stranding the machine
    // with no internet after disconnect.
    let allowed_ips = expand_default_v4(allowed_ips);
    for cidr in &allowed_ips {
        let _ = cmd("ip").args(["route", "del", cidr]).output();
    }

    // Remove the Local Network Sharing routes too.
    //
    // These were installed and NEVER removed, so they outlived the session
    // pointing at a gateway that stops existing the moment the user changes
    // network — a stale RFC1918 route to a dead gateway silently blackholes LAN
    // traffic long after Birdo is closed. Unconditional and best-effort: if LAN
    // sharing was off there is nothing to delete and the command simply fails.
    // ONLY if we added them, and QUALIFIED by gateway + device.
    //
    // Unconditional deletion repeated the mistake just fixed for the default
    // route: removing something we never installed. With sharing OFF we add
    // nothing, so every delete targeted the user's own routes. And a bare
    // `ip route del <prefix>` matches the lowest-metric entry regardless of
    // device — on a normal desktop that is NetworkManager's link-scope
    // 169.254.0.0/16, which we must never touch.
    //
    // Qualifying with via/dev is the same argv shape the ADD uses, so a delete
    // can only ever match a route of ours.
    if local_network_sharing {
        if let (Some(gw), Some(iface)) = (default_gateway, default_interface) {
            for cidr in LAN_SHARING_CIDRS {
                let _ = cmd("ip")
                    .args(["route", "del", cidr, "via", gw, "dev", iface])
                    .output();
            }
        }
    }
    tracing::info!("Removed VPN routes");
}

/// Capture current network configuration for later restoration.
async fn capture_network_snapshot() -> Result<NetworkSnapshot, String> {
    let default_gateway = get_default_gateway().ok();
    let default_interface = get_default_interface().ok();

    // Check if systemd-resolved is active
    let uses_resolved = cmd("systemctl")
        .args(["is-active", "--quiet", "systemd-resolved"])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false);

    // ALWAYS capture the raw /etc/resolv.conf bytes, regardless of the
    // resolved check above. configure_dns overwrites the file whenever it is
    // not the systemd stub — INCLUDING on the host class documented at
    // resolv_conf_uses_resolved() where the resolved UNIT is active but
    // resolv.conf is a plain file (Ubuntu images with a replaced resolv.conf,
    // Debian resolvconf, NetworkManager dns=default, WSL, containers).
    // Gating the backup on `systemctl is-active` stored None on exactly those
    // hosts, so disconnect left the file pointing at tunnel resolvers that no
    // longer existed: DNS dead system-wide until something else rewrote it.
    // None only when the file itself is unreadable.
    let resolv_conf_backup = std::fs::read_to_string("/etc/resolv.conf").ok();

    // Capture current DNS servers
    let dns_servers: Vec<String> = if uses_resolved {
        // Read from resolvectl
        let output = cmd("resolvectl")
            .args(["status", "--no-pager"])
            .output()
            .map_err(|e| format!("Failed to get DNS status: {}", e))?;

        let stdout = String::from_utf8_lossy(&output.stdout);
        stdout
            .lines()
            .filter(|l| l.contains("DNS Servers:") || l.contains("Current DNS Server:"))
            .flat_map(|l| {
                l.split(':')
                    .nth(1)
                    .map(|s| s.trim().to_string())
                    .into_iter()
                    .filter(|s| !s.is_empty())
            })
            .collect()
    } else {
        // Read from the /etc/resolv.conf contents captured above
        resolv_conf_backup
            .as_deref()
            .unwrap_or_default()
            .lines()
            .filter(|l| l.starts_with("nameserver"))
            .filter_map(|l| l.split_whitespace().nth(1).map(|s| s.to_string()))
            .collect()
    };

    Ok(NetworkSnapshot {
        dns_servers,
        default_gateway,
        default_interface,
        uses_systemd_resolved: uses_resolved,
        resolv_conf_backup,
        // Set by start() once configure_dns has actually written the file.
        resolv_conf_pinned: false,
    })
}

/// Get the default gateway IP from the routing table.
fn get_default_gateway() -> Result<String, String> {
    let output = cmd("ip")
        .args(["route", "show", "default"])
        .output()
        .map_err(|e| format!("Failed to get default route: {}", e))?;

    let stdout = String::from_utf8_lossy(&output.stdout);
    // default via 192.168.1.1 dev eth0
    stdout
        .split_whitespace()
        .skip_while(|&w| w != "via")
        .nth(1)
        .map(|s| s.to_string())
        .ok_or_else(|| "Could not determine default gateway".to_string())
}

/// Get the default network interface name.
fn get_default_interface() -> Result<String, String> {
    let output = cmd("ip")
        .args(["route", "show", "default"])
        .output()
        .map_err(|e| format!("Failed to get default route: {}", e))?;

    let stdout = String::from_utf8_lossy(&output.stdout);
    // default via 192.168.1.1 dev eth0
    stdout
        .split_whitespace()
        .skip_while(|&w| w != "dev")
        .nth(1)
        .map(|s| s.to_string())
        .ok_or_else(|| "Could not determine default interface".to_string())
}

// ─────────────────────────────────────────────────────────────────────────────
// F-001 verification
//
// This exercises the REAL install/remove functions against the REAL ip6tables
// binary, rather than asserting on a duplicated copy of the argv. It is the only
// part of the F-001 Linux fix that can be checked without a dual-stack network,
// and CI runs it as root on ubuntu-latest (see .github/workflows/tests.yml).
//
// Ignored by default so a normal `cargo test` on a dev box never touches the
// host firewall: run explicitly with `--ignored`, as root.
// ─────────────────────────────────────────────────────────────────────────────
#[cfg(test)]
mod ipv6_leak_block_tests {
    use super::*;

    fn ip6tables_available() -> bool {
        cmd("ip6tables")
            .arg("-L")
            .arg("-n")
            .output()
            .is_ok_and(|o| o.status.success())
    }

    fn chain_dump() -> String {
        cmd("ip6tables")
            .args(["-S"])
            .output()
            .map(|o| String::from_utf8_lossy(&o.stdout).to_string())
            .unwrap_or_default()
    }

    #[test]
    #[ignore = "mutates the host firewall; run as root via --ignored (CI does)"]
    fn install_then_remove_leaves_no_trace() {
        assert!(
            ip6tables_available(),
            "ip6tables must be present and usable (are we root?)"
        );

        // Clean slate in case a previous run died mid-way.
        remove_ipv6_leak_block();

        install_ipv6_leak_block().expect("install_ipv6_leak_block failed");

        let dump = chain_dump();
        assert!(
            dump.contains(&format!("-N {IPV6_BLOCK_CHAIN}")),
            "chain was not created:\n{dump}"
        );
        assert!(
            dump.contains(&format!("-A OUTPUT -j {IPV6_BLOCK_CHAIN}")),
            "OUTPUT jump was not installed — the chain would never be evaluated:\n{dump}"
        );
        // The whole point: routable IPv6 must terminate in a DENY rule. REJECT is
        // preferred over DROP — a silent drop made our OWN dual-stack
        // control-plane requests stall until timeout instead of falling through
        // to IPv4 — but a kernel without ip6t_REJECT falls back to DROP. Either
        // satisfies the default-deny guarantee this test exists to protect, so
        // assert on the guarantee rather than on one specific target.
        assert!(
            dump.contains(&format!("-A {IPV6_BLOCK_CHAIN} -j REJECT"))
                || dump.contains(&format!("-A {IPV6_BLOCK_CHAIN} -j DROP")),
            "default-deny rule missing — the block would pass everything:\n{dump}"
        );
        // Link-local must stay permitted or the host's own NDP breaks.
        assert!(
            dump.contains("fe80::/10") && dump.contains("ff02::/16"),
            "link-local/multicast allowances missing — NDP would break:\n{dump}"
        );
        // Regression guard: a blanket ICMPv6 accept would let `ping6 <global>`
        // out and disclose the real address — a smaller version of this leak.
        assert!(
            !dump.contains("-p ipv6-icmp -j ACCEPT"),
            "blanket ICMPv6 ACCEPT is back; global ping6 would leak:\n{dump}"
        );

        // Idempotent: installing twice must not stack duplicate OUTPUT jumps.
        install_ipv6_leak_block().expect("second install failed");
        let dump2 = chain_dump();
        let jumps = dump2
            .lines()
            .filter(|l| l.trim() == format!("-A OUTPUT -j {IPV6_BLOCK_CHAIN}"))
            .count();
        assert_eq!(jumps, 1, "duplicate OUTPUT jumps stacked:\n{dump2}");

        remove_ipv6_leak_block();
        let after = chain_dump();
        assert!(
            !after.contains(IPV6_BLOCK_CHAIN),
            "teardown left state behind — the host would stay without IPv6:\n{after}"
        );
    }
}
