#!/usr/bin/env pwsh
# =============================================================================
# update-cert-pins.ps1 — P2-16: Update CERT_PINS_SHA256 in client.rs from live cert
#
# Fetches the leaf certificate from birdo.app, computes the full DER SHA-256
# hash, and updates the CERT_PINS_SHA256 array in src-tauri/src/api/client.rs.
#
# Usage:
#   .\scripts\update-cert-pins.ps1
#   .\scripts\update-cert-pins.ps1 -Host birdo.app -DryRun
# =============================================================================
[CmdletBinding()]
param(
    [string]$HostName = "birdo.app",
    [int]$Port = 443,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

$clientRsPath = Join-Path $PSScriptRoot "..\src-tauri\src\api\client.rs"
if (-not (Test-Path $clientRsPath)) {
    Write-Error "client.rs not found at $clientRsPath"
    exit 1
}

Write-Host "Fetching leaf certificate from ${HostName}:${Port}..." -ForegroundColor Cyan

# Use .NET to get the server certificate
$tcp = [System.Net.Sockets.TcpClient]::new($HostName, $Port)
$ssl = [System.Net.Security.SslStream]::new($tcp.GetStream(), $false, { $true })
$ssl.AuthenticateAsClient($HostName)
$cert = $ssl.RemoteCertificate
$ssl.Close()
$tcp.Close()

if (-not $cert) {
    Write-Error "Failed to retrieve certificate from ${HostName}:${Port}"
    exit 1
}

$x509 = [System.Security.Cryptography.X509Certificates.X509Certificate2]::new($cert)
$derBytes = $x509.RawData
$sha256 = [System.Security.Cryptography.SHA256]::Create()
$hash = $sha256.ComputeHash($derBytes)
$pin = [Convert]::ToBase64String($hash)

$subject = $x509.Subject
$expiry = $x509.NotAfter.ToString("yyyy-MM-dd")

Write-Host "  Subject: $subject" -ForegroundColor Green
Write-Host "  Expires: $expiry" -ForegroundColor Green
Write-Host "  DER SHA-256: $pin" -ForegroundColor Yellow

# Also generate SPKI pin for Android/OkHttp
$pubKey = $x509.PublicKey.EncodedKeyValue.RawData
# Prepend algorithm identifier for SPKI encoding
$spkiHash = $sha256.ComputeHash($x509.PublicKey.ExportSubjectPublicKeyInfo())
$spkiPin = [Convert]::ToBase64String($spkiHash)
Write-Host "  SPKI SHA-256: $spkiPin (for Android/OkHttp)" -ForegroundColor Yellow

if ($DryRun) {
    Write-Host "`nDry run — no files modified." -ForegroundColor Magenta
    Write-Host "`nPaste into client.rs CERT_PINS_SHA256:"
    Write-Host "    `"$pin`",  // leaf: $HostName (expires $expiry)"
    exit 0
}

# Read client.rs and update the CERT_PINS_SHA256 array
$content = Get-Content $clientRsPath -Raw

# Pattern: match the CERT_PINS_SHA256 array content between &[ and ];
$pattern = '(?s)(const CERT_PINS_SHA256: &\[&str\] = &\[)(.*?)(\];)'

if ($content -notmatch $pattern) {
    Write-Error "Could not find CERT_PINS_SHA256 array in client.rs"
    exit 1
}

$newArrayContent = @"

    // Auto-generated by update-cert-pins.ps1 — do not edit manually.
    // Run: .\scripts\update-cert-pins.ps1
    "$pin",  // leaf: $HostName (expires $expiry)
    // -- Next cert pin slot --
    // Add new pin here BEFORE removing old one during cert rotation.

"@

$newContent = $content -replace $pattern, "`$1$newArrayContent`$3"
Set-Content $clientRsPath -Value $newContent -NoNewline

Write-Host "`nUpdated $clientRsPath with new cert pin." -ForegroundColor Green
Write-Host "Run 'cargo build' to verify the build succeeds." -ForegroundColor Cyan
